-- 코드를 입력하세요
SELECT DISTINCT p.PRODUCT_ID, p.PRODUCT_NAME, SUM(p.PRICE*o.AMOUNT) OVER(PARTITION BY p.PRODUCT_NAME) as TOTAL_SALES
FROM FOOD_PRODUCT p
JOIN FOOD_ORDER o ON p.PRODUCT_ID = o.PRODUCT_ID
WHERE o.PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
ORDER BY TOTAL_SALES DESC, p.PRODUCT_ID