-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) as 전체주소, CONCAT(LEFT(u.TLNO, 3), '-', SUBSTRING(u.TLNO, 4, 4), '-', RIGHT(u.TLNO, 4)) as 전화번호
FROM USED_GOODS_USER u
JOIN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3
) b
ON u.USER_ID = b.WRITER_ID
ORDER BY u.USER_ID DESC;
