SELECT ID, 
    CASE WHEN rn <= cnt / 4 THEN 'CRITICAL'
    WHEN rn <= cnt / 2 THEN 'HIGH'
    WHEN rn <= cnt * 3/4 THEN 'MEDIUM'
    ELSE 'LOW'
    END AS COLONY_NAME
FROM (
    SELECT ID, ROW_NUMBER() OVER (ORDER BY SIZE_OF_COLONY DESC) AS rn,
    COUNT(*) OVER() AS cnt
    FROM ECOLI_DATA
) T
ORDER BY ID;