-- 코드를 작성해주세요
SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n ON i.FISH_TYPE = n.FISH_TYPE
WHERE i.LENGTH = (
SELECT MAX(i2.LENGTH)
FROM FISH_INFO i2
WHERE i.FISH_TYPE = i2.FISH_TYPE)
ORDER BY i.ID